version: "3.8"

services:
  backend:
    build:
      context: .                 # Root, where the backend Dockerfile is
      dockerfile: Dockerfile     # Explicitly state it's here
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
    networks:
      - app-network
      

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
