apiVersion: v1
kind: Service
metadata:
  name: doc-classifier-service
spec:
  selector:
    app: doc-classifier
  ports:
    - protocol: TCP
      port: 80            # External port
      targetPort: 8000    # Container port
  type: NodePort          # Change to LoadBalancer if needed
